### ISSUE TITLE
return only the last line

### ISSUE THREAD

**Issue by bsocius** [jandre/always-tail#10]
Hi Everybody,

I have noticed that the always-tail package reads the entire file. Is there a way to only return the last line of the file or like an option where one could set how many lines one wants to be returned. Just like the tail  command on Linux which allows me to set the lines returned with the -n flag.

**Comment by bgotink** [comment]
Something like this has been implemented already, the master branch allows you to enter a number of bytes to skip when reading the file. By default, the module will now ignore the contents in the file when the Tail starts.

This is not yet released on npm though. Can you publish a new version, @jandre?

**Comment by jandre** [comment]
Published 0.2.0 - thanks!

**Comment by bsocius** [comment]
Thanks :)
